apiVersion: v1
kind: Pod
metadata:
  name: hello-k8s-pod
spec:
  containers:
  - name: hello-k8s-container
    image: hello-k8s:v1.0.1
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8080