apiVersion: v1
kind: Service
metadata:
  name: hello-k8s-service
spec:
  type: NodePort
  selector:
    app: hello-k8s  # убедись, что метка совпадает с метками в Pod-манифесте
  ports:
    - protocol: TCP
      port: 80        # порт, по которому будет доступен сервис
      targetPort: 8080 # порт контейнера